### ISSUE TITLE
When Update to 4.22.9.0,Notify Bot was fail

### ISSUE THREAD

**Issue by gamegeartw** [microsoft/botbuilder-dotnet#6876]
## Version
What package version of the SDK are you using. 
Microsoft.Bot.Builder 4.22.9.0

## Describe the bug
 I use Microsoft.Bot.Builder 4.22.9.0 and encounter a CS0012 error indicating that the type 'BotAdapter' is defined in an assembly that is not referenced. The error message suggests adding a reference to 'Microsoft.Bot.Builder, Version=4.22.7.0, Culture=neutral, PublicKeyToken=null', but this version does not match the one I am using.

## To Reproduce
1.	Use TeamsToolKit and Create a new .NET 8 project  (Select Notification Bot)
2.	Update  Microsoft.Bot.Builder 4.22.9.0 package.
3.	Attempt to use the 'BotAdapter' type in the code.
4.	See error CS0012.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots to help explain your problem.![Image](https://github.com/user-attachments/assets/f7d2565a-65c7-4fa1-b860-1732772a9bcd)

## Additional context
The issue seems to be related to a mismatch in the assembly version referenced in the error message and the actual package version being used.

**Comment by Nivedipa-MSFT** [comment]
@gamegeartw - Thank you for bringing this issue to our attention. We will look into it and get back to you shortly.

**Comment by tracyboehrer** [comment]
This will not be addressed prior to Bot Framework SDK deprecation EOM December 2025.
